apiVersion: v1
kind: Service
metadata:
  name: r-http-ping
  labels:
    app: r-http-ping
    service: r-http-ping
spec:
  type: NodePort
  ports:
  - name: http-r-http-ping
    port: 8080
    targetPort: 8080
  selector:
    app: r-http-ping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-http-ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r-http-ping
      version: v0.1.0
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: r-http-ping
        version: v0.1.0
    spec:
      containers:
      - image: ssingh3339/r-http-ping:latest
        imagePullPolicy: Always
        name: r-http-ping
        ports:
        - containerPort: 8080
        resources: 
            limits: 
              cpu: ".5"
              memory: 100Mi
            requests: 
              cpu: ".25"
              memory: 50Mi